### ISSUE TITLE
Visicam still broken

### ISSUE THREAD

**Issue by DxDMorgan** [t-oster/VisiCam#39]
Visicam looks like it has been abandoned. This is a pity.
The problem seems to always be the same as indicated by the previous issue. The Java dependencies used no longer exist for a few updates.
If the project is dead, it would be nice if the github was closed.

**Comment by t-oster** [comment]
Well, for anyone interested this may be a good starting point, but we should add a note to the readme.

**Comment by mgmax** [comment]
Which issue do you refer to? To the Raspi integration?
Yes, the Raspi integration is broken, but this is a special feature and not needed for running VisiCam on any other system. Of course it would be great to have a simple installer script that you run on some RasPi installation. For more discussion please use the original issue.

Any average PC is good enough. The [Dockerfile](https://github.com/t-oster/VisiCam/blob/master/Dockerfile) is a well-tested description of how to build VisiCam. I can confirm that VisiCam successfully runs on Ubuntu 20.04 . I am seeing people use it successfully every day in a FabLab - last checked a few days ago :-)

So VisiCam is definitely not abandoned.

The documentation is not ideal; many things are duplicate and inconsistent between the README, the [Wiki](https://github.com/t-oster/VisiCam/wiki) and various old Wiki pages. I am looking forward to your contribution.

Please feel invited to improve the documentation and to provide a clear bug report. Open-source projects depend on people such as you -- Do good and the world will become better :-)
