### ISSUE TITLE
Easier installation on Raspberry Pi?

### ISSUE THREAD

**Issue by peteruithoven** [t-oster/VisiCam#5]
So I finally got it installed on the Raspberry Pi, see the following page. 
https://github.com/t-oster/VisiCam/wiki/Raspberry-Pi-installation-(Raspbian)

But this is quite some work. OpenCV compilation takes > 3 hr's, JavaCV compilation takes almost an hour. So I'm looking for ways to make this easier. Is there for example any way to share my compiled version of opencv? 

I will soon do a fork request with my compiled javacpp.jar and a startup shell script.

**Comment by FroChr123** [comment]
Maybe this issue can be closed now? :)
We have a full SD card image and improved compilation times now, it will probably not get anymore better than this.

**Comment by peteruithoven** [comment]
Agreed.
